### ISSUE TITLE
Create account screen

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/firefly#2]
### Todo
- [x] sign in / out with google
- [x] click account to go to account details page
- [x] user can link their spotify/google to enable spotify/google tracks

**Comment by michaelfitzhavey** [comment]
closed as we are currently using google sign in
